### ISSUE TITLE
Should we create a Sage standard mongo repo?

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/mongo#2]
There was a mongo repository created for the SBCP as well: https://github.com/Sage-Bionetworks/sbcp-mongo.  Would it be worth it to create one `mongo` github + dockerhub instead of one per project?

**Comment by tschaffter** [comment]
I created this repo based on [sbcp-mongo](https://github.com/Sage-Bionetworks/sbcp-mongo) - instead of reusing it - because [sbcp-mongo](https://github.com/Sage-Bionetworks/sbcp-mongo) CI/CD workflow tightly linked to the SBCP deployment: each time the repo is updated the sbcp-mongo docker image is rebuilt and redeployed on the development/production EC2.

We could move this repo to Sage Bionetworks as you suggest and publish the image to DockerHub using the new Sage DockerHub service user. If we meet another SBCP use case, one could fork Sage mongo repo and customize the CI/CD file.

A possibly better alternative would be to not rely on GitHub/DockerHub CI/CD workflow for auto-deployment, e.g. by having an agent running on an EC2 that check if there is a new version of a Docker image available. I'm sure that there are already solutions available to do this.

If you agree with this, I'll move with the GitHub / DockerHub transfer to Sage space.
